### ISSUE TITLE
uikit.min.css after theme.css

### ISSUE THREAD

**Issue by Smeaven** [DrivenNetwork/pagekit-listings#8]
Sometimes 'listings' does load the uikit.min.css file after the the theme.css which causes some style issues.

``` html
<link href="/packages/pagekit/theme-one/css/theme.css?v=c2f5" rel="stylesheet">
<link href="/packages/driven/listings/assets/css/uikit.min.css?v=c2f5" rel="stylesheet">
```

If I change the order of this sheets, the page looks as it should be. But I could't figure out, where you load this stylesheet exactly in your code.

Thanks

**Comment by tobbexiv** [comment]
The second uikit is loaded here:

https://github.com/DrivenNetwork/pagekit-listings/blob/master/views/list.php#L2

However I do not understand why you are loading a second uikit theme? What is the purpose of it? Uikit should be loaded by the theme and you should only inject your custom css without changing uikit. Otherwise you might break the theme as it happens in this case.

**Comment by luisreyes** [comment]
The library is required for the custom templating features. If the theme 'for some reason' is built without it then the dependency won't be there. But you are correct it shouldn't be loaded twice. I'll look into this soon.

**Comment by tobbexiv** [comment]
I'd assume this should be in the theme. If not present there: Don't care. Otherwise you might "crash" the theme by overwriting parts of it.

Another idea would be that you don't use uikit classes but your own class names and only for your few specific things in the templates. Then you will not overwrite theme stylings.

**Comment by luisreyes** [comment]
I'm thinking... Make it configurable. Turn it ON or OFF. There are many users by now and removing it would break their apps. ON would use listing's ui-kit.css and OFF would inherit the theme's one.

I don't want to write a custom one since with uikit's you have a long list of classes to use.

Thoughts?

**Comment by tobbexiv** [comment]
Make it configurable would be one option. But one question I have is which features you really need that are not available in a normal theme? The core features are usually automatically included (grid, flex, ...) and not changed. So only classes you really edited and changed in the templates need to be copied. And to me this seems like they are not that many?

**Comment by luisreyes** [comment]
Removed the css reference from the [list.php](https://github.com/DrivenNetwork/pagekit-listings/blob/b22b14ceab07269e31c434cb614fbdac305e228c/views/list.php) page.
No more duplicates.
